"""Regression contracts for dynamically rendered desktop form controls.

The canvas and director workflow are assembled from JavaScript templates, so
their selects do not go through the static HTML accessibility audit.  Keep the
high-value engine/camera controls explicitly named to prevent WebView screen
readers from exposing a list of anonymous comboboxes.
"""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _text(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def test_dynamic_engine_and_canvas_selects_keep_explicit_names() -> None:
    panel = _text("static/js/video-workflow-panel.js")
    canvas = _text("static/js/canvas.js")
    smart = _text("static/smart-canvas.html")

    # Every engine slot is generated by the same template; naming the slot in
    # the label keeps the eight provider/model controls distinguishable.
    assert 'data-vwf="eng-provider" aria-label="' in panel
    assert 'data-vwf="eng-model"' in panel and 'placeholder="' in panel and 'aria-label="' in panel
    assert 'data-vwf="eng-base"' in panel and 'aria-label="' in panel
    assert 'data-cam-preset-select aria-label="${escapeHtml(cameraPresetLabel)}"' in panel
    assert "cameraPresetKey === 'videoWf.cameraPreset'" in panel
    assert '"videoWf.cameraPreset"' in _text("static/js/i18n/common.js")

    # Legacy canvas nodes are also generated dynamically and must not regress
    # to anonymous comboboxes when a node is refreshed.
    assert 'class="select-lite video-provider"' in canvas
    assert 'class="select-lite video-model"' in canvas
    assert 'class="select-lite asset-kind" aria-label=' in canvas
    video_block = canvas[canvas.index('class="select-lite video-provider"'):canvas.index('const providerSelect', canvas.index('class="select-lite video-provider"'))]
    assert 'aria-label=' in video_block

    # The smart composer is static HTML but its engine selector is the first
    # control keyboard users encounter on an empty canvas.
    assert '<select id="engineSelect" class="engine-select" aria-label="生成引擎"' in smart
